### ISSUE TITLE
Using react's hooks api

### ISSUE THREAD

**Issue by hagai-reuveni** [coatue-oss/react2angular#100]
Hi,
I'm trying to embed a small react component in which one of the children is using react's hook api and I keep getting this error: "Invariant Violation: Hooks can only be called inside the body of a function component".
Needless to say that it's in a function and it only crashes when I'm trying to embed it.
Do you have any idea why ?

Thanks,
H.

**Comment by ermakovich** [comment]
what `react-dom` version you have? I had the same issue and it fixed after updating `react-dom` to 16.8.3.

**Comment by bcherny** [comment]
I'd ask on Stackoverflow, and tag your question with React. This is likely unrelated to react2angular.

**Comment by hagai-reuveni** [comment]
First of all - thanks @ermakovich and @bcherny(!)

Unfortunately, I do use react-dom 16.8.3 and the app fails only when react2angular tries to render a component that (one of the child components) uses hooks. When I'm rendering the same app without react2angular all is fine :(.

**Comment by tobiasletcher-ap** [comment]
> First of all - thanks @ermakovich and @bcherny(!)
> 
> Unfortunately, I do use react-dom 16.8.3 and the app fails only when react2angular tries to render a component that (one of the child components) uses hooks. When I'm rendering the same app without react2angular all is fine :(.
> 
> @ermakovich - would you mind sharing your code?
> 
> H.

Were you able to work out what the issue was?

**Comment by matthewborgman** [comment]
@ermakovich, @hagai-reuveni , or @tobiasletcher-ap are _any_ of you able to share your code that (hopefully) resolved this issue with hooks? (I confirmed I'm on react-dom 16.13.1.) Thanks!

**Comment by tobiasletcher-ap** [comment]
> @ermakovich, @hagai-reuveni , or @tobiasletcher-ap are _any_ of you able to share your code that (hopefully) resolved this issue with hooks? (I confirmed I'm on react-dom 16.13.1.) Thanks!

If I recall the reason I asked my question, our issue was a bad webpack setup in shared lib, so there were 2 copies of react which hooks does not allow for. So it wasn't react2angular related.

**Comment by matthewborgman** [comment]
Thank you for replying, @tobiasletcher-ap!

It turns out I had a similar situation re: 2 copies of React due to a shared library. 

Hopefully this information is helpful to someone else too.
