### ISSUE TITLE
Nested react components

### ISSUE THREAD

**Issue by lhoover12** [coatue-oss/react2angular#11]
Hey, so I'm currently using react2angular and Im having problems with nested react elements. I was wondering if you supported this.

```html
<react-select
  label="'this is a label'"
  hintText="'hintText''">

  <react-option
  value="1"
  primaryText="Option 1">
  </react-option>

  <react-option
  value="2"
  primaryText="Option 2">
  </react-option>

  <react-option
  value="3"
  primaryText="Option 3">
  </react-option>

</react-select>

```
So i have this react component for select, and a react component for the options, and was wondering how to nest the options in the select component.

**Comment by bcherny** [comment]
Hi @lhoover12. Unfortunately, react2angular does not support transclusion/children (see [unit test](https://github.com/coatue-oss/react2angular/blob/master/test.tsx#L161)) - perhaps we should make this more clear in the docs.

As a workaround, you could modify your `react-select` component and pass your options in as a prop.

Let me know if that helps!

**Comment by lhoover12** [comment]
Thanks! This has been very helpful.

**Comment by tiny-dancer** [comment]
@bcherny curious, is it in the plans to support this?

**Comment by bcherny** [comment]
@tiny-dancer This is definitely something worth investigating. We would need to:

1. Mark the component as `transclude: true`
2. Compile transcluded children in the component's scope
3. Convert the compiled elements to JSX, and pass them to the component as children

For step 2, the [`$transclude` service](https://docs.angularjs.org/api/ng/service/$compile#-controller-) could be a good way to go.

Step 3 is where things get hairy. Ideally we would pass the DOM provided by `$transclude` through something like [htmltojsx](https://www.npmjs.com/package/htmltojsx) and into the React component. Alternatively we could pass in transcluded DOM via `this.props` or `this.context`, and make rendering it the consumer's responsibility.

What do you think?

**Comment by tiny-dancer** [comment]
i'm not currently familiar with the innards of this flow so not sure how much help I can be but it is interesting problem to solve.

option 1 for step 3 sounds like the preferable solution.

> Alternatively we could pass in transcluded DOM via this.props or this.context, and make rendering it the consumer's responsibility.

what would that look like on the react side?  would it lead to the need for react2angular specific logic in the react component (rendering raw html)?

**Comment by bcherny** [comment]
> option 1 for step 3 sounds like the preferable solution.

Agreed.

> what would that look like on the react side? would it lead to the need for react2angular specific logic in the react component (rendering raw html)?

It would. For example:

```jsx
class App extends Component {
  render() {
    return <div ref={this.div = div} />
  }
  componentDidUpdate() {
    this.div.appendChild(this.props.transcludedChildren)
  }
}
```

**Comment by bcherny** [comment]
Tracking this feature here - https://github.com/coatue-oss/react2angular/issues/12
