### ISSUE TITLE
No documentation on function binding incompatibility

### ISSUE THREAD

**Issue by texonidas** [coatue-oss/react2angular#110]
I will putting a pull request in in the next few hours, but for paper trail I will log the issue here first.

Currently the documentation contains no references to the distinction between AngularJS function bindings and React function props. AngularJS function bindings will invoke the expression when the function binding is called, whereas React will directly pass the values from the prop. In hindsight it is somewhat obvious, however I still think it bears stating explicitly in the readme that you need to set the binding/prop directly to the value of the function you are invoking.

There are a handful of issues people have logged in the past around this issue, so I think adding the distinction will be useful to prevent any confusion.

**Comment by ghost** [comment]
👍 thanks for the PR
