### ISSUE TITLE
React 18 upgrade

### ISSUE THREAD

**Issue by karesztrk** [coatue-oss/react2angular#148]
Hello all,

I would like to reuse this library in React 18. However, the current implementation of `react2angular` doesn't support it. Its mainly because the peer dependency points to an older version.
With your acceptance, I would like to republish this library (under the same license) using the new [React 18 render](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html).
Let me know what do you think.

**Comment by karesztrk** [comment]
Hey everybody. 
I've forked and rebuilt the library @ https://github.com/karesztrk/react18-to-angularjs
Let me know if there's anything to improve.
By the way, im also fine if you allow me to publish the changes into this repository (currently I do not have push rights to this repo)

**Comment by tmikeschu** [comment]
@karesztrk thank you! It looks like 1.0.0 doesn't include types in the bundle. Perhaps from `noEmit: true`. Was that intentional?
![image](https://user-images.githubusercontent.com/19894032/175369530-839b4150-d50f-42f9-a674-530c949374b4.png)

**Comment by karesztrk** [comment]
Hey @tmikeschu. Yes, that was intentional. The next release will contain it. You can check it in the dev branch.
I was struggling with the unit tests (integrating React 18 renderer together with [Angular Mock](https://www.npmjs.com/package/angular-mocks)). That's why it's delayed.

**Comment by tmikeschu** [comment]
Right on, thanks!
