### ISSUE TITLE
Using directives in react component

### ISSUE THREAD

**Issue by chasedeanda** [coatue-oss/react2angular#18]
Are custom directives supported out of the box or is there something special that needs to be done to get them working. For instance:
```
class MyComponent extends React.Component {
    render(){
        return <custom-chart></custom-chart>
    }
}
```
When I inspect this html, it looks like it's just spitting this back out as if it were valid HTML. How do I get custom directives working in my component?

**Comment by bcherny** [comment]
Hi @chasedeanda! There is no magic going on - that's a regular React component with a regular React render function.

If your `CustomChart` element is a React component, you want:

```jsx
class MyComponent extends React.Component {
    render(){
        return <CustomChart />
    }
}
```

If your `CustomChart` component is an Angular component, you want something like:

```jsx
let $injector
angular
  .module('myModule')
  .run(['$injector', function(_$injector) { $injector = _$injector }])
const CustomChart = angular2react('customChart', CustomChartComponent, $injector)

class MyComponent extends React.Component {
    render(){
        return <CustomChart />
    }
}
```

See https://github.com/coatue-oss/angular2react for more usage info.

**Comment by chasedeanda** [comment]
In my example, `<custom-chart></custom-chart>` is an angular directive, not component. I looked at angular2react, but it seems like it only supports angular components. Directives and components are different in angular, so I was wondering how to get them working. I guess I'll do some more experimentation and see what I come up with. Thanks for the reply.

**Comment by bcherny** [comment]
You'll have to either convert it to an Angular component or React component, or manually wrap it in one.

The conversion from Angular directive => component is pretty mechanical (I was thinking about automating it at one point), and should be straight forward.

**Comment by chasedeanda** [comment]
Okay, that may be the best way to move forward. Thanks for your help 👍
