### ISSUE TITLE
Using Angular 1 factories on react components

### ISSUE THREAD

**Issue by dbabaioff** [coatue-oss/react2angular#29]
What's the best/ recommend way to use a angular factory inside a react component?
Like,  how can I import/inject inside the component? Do I need a scope apply after calling the factory function?

**Comment by bcherny** [comment]
Hi @dbabaioff! You have two options:

1. Convert the factory to a regular (non-Angular) factory. For example:

    ```js
    // before
    angular.factory('foo', function() {
      return {...}
    })

    // after
    export let Foo = {...}
    angular.factory('foo', function() {
      return Foo
    })
    ```

2. Expose your factory to ES6 exports ([example](https://github.com/bcherny/ngimport/#using-this-technique-to-wrap-your-own-legacy-modules)).

(1) is preferable, but if your factory depends on a lot of other DI'd providers then you will have to repeat (1) for each of them too. (2) is a way to short-circuit the process, so you can expose a single provider without having to convert them each to (1).

Hope that helps!
