### ISSUE TITLE
Cannot render component if propTypes is omitted

### ISSUE THREAD

**Issue by youngzhaosignifyd** [coatue-oss/react2angular#31]
First of all, thanks so much for the library. Very good work!

I am creating a react component that doesn't require any bindings from the angular app. So I just omit the propTypes in the react component and in the react2angular function. But in this way the react component cannot be rendered. Is this a bug or a desired behavior?  

Example:

```
// React component
import { Component } from 'react'

class MyComponent extends Component {
  render() {
    return <div>foo</div>
  }
}

// angular
angular
  .module('myModule', [])
  .component('myComponent', react2angular(MyComponent))
```

The react component is not rendered unless I add a non-empty in `react2angular`: 

```
// I don't need foo propType but I have to add something in the second argument
// to make react2angular work
angular
  .module('myModule', [])
  .component('myComponent', react2angular(MyComponent, 'foo'))
```

**Comment by bcherny** [comment]
Thanks @youngzhaosignifyd! I added some explicit tests for component that take no props in 3653f8a. The `component('myComponent', react2angular(MyComponent))` should work fine.

Can you post a complete, self contained repro case? I suspect there's something else going on.

**Comment by youngzhaosignifyd** [comment]
@bcherny:

Thanks for the quick response! 

You are right. It is caused by some other issue. We are using angular 1.4 a another library [angular-component](https://github.com/toddmotto/angular-component) to make the angular.component work. I think that causes the issue. 

I just created a repo to make sure the `component('myComponent', react2angular(MyComponent))` syntax works: https://github.com/zhaocnus/react2angular-test

I will close this one.
