### ISSUE TITLE
Make react + react-dom a peerDependency to allow compatibility with projects using React v16

### ISSUE THREAD

**Issue by HipsterZipster** [coatue-oss/react2angular#33]
Currently React and React-Dom are set as dependencies in the package.json for ^15.6.1, which does not fit the standard model for React libraries, where they list them as peerDeps instead and extend the acceptable range to >=15 (or higher for the minimum). This causes npm to download another version of React and causes a variety of issues. Considering that any React project already has their own version declared, this should make the library much more flexible.

**Comment by bcherny** [comment]
PRs are welcome!

**Comment by HipsterZipster** [comment]
That's great news. Will try to find time for it this weekend.

**Comment by capaj** [comment]
@bcherny just opened it

**Comment by bcherny** [comment]
```
+ react2angular@2.0.0
```
