### ISSUE TITLE
Not working with AngularJS Component Polyfill

### ISSUE THREAD

**Issue by mattiascaricato** [coatue-oss/react2angular#42]
Using AngularJS 1.4 with the [angular-component polyfill](https://github.com/toddmotto/angular-component) only the first prop in the array of bindings is available. All the rest are undefined until you change a binding and you run a new digest cycle.

Here is an example where you can reproduce the issue -> https://stackblitz.com/edit/react2angular-binding-issue

**Comment by bcherny** [comment]
Hi @mattiascaricato! I believe this is an Angular behavior, and is not related to React or react2angular.

See my forked repro here - same behavior with just plain Angular: https://stackblitz.com/edit/react2angular-binding-issue-8ccxl7?file=react-component.js.

If that's right, I can close this issue for you.

**Comment by bcherny** [comment]
For the record, here's the usual React way of working around that issue: https://stackblitz.com/edit/react2angular-binding-issue-wgykee?file=react-component.js.

Note that as you convert your code to React, this issue will go away.

**Comment by canda** [comment]
@bcherny thank you very much for time. Great library 🥇 

On your first example you can see the issue I think.

On angular 1.4 + polyfill $onChanges is called 3 times. Each time setting a new bind.
![image](https://user-images.githubusercontent.com/1220263/31098155-135f8228-a798-11e7-9537-812775fb75f7.png)

Shouldn't the react component re-render on each $onChanges? and on the final re-render have the 3 props set?

Here you can see the angular component do render after the final onChanges and so displays the 3 bindings
https://stackblitz.com/edit/react2angular-binding-issue-renwmw?file=react-component.js

On react it doesn't :( 
https://stackblitz.com/edit/react2angular-binding-issue-ltnt5s?file=react-component.js

**Comment by bcherny** [comment]
@canda Thanks for the details. I just published react2angular@3.0.1. Give that a try - it should fix your issue.

**Comment by canda** [comment]
Thanks man, works like a charm.
For future reference, this was the commit that fixed this
https://github.com/coatue-oss/ngcomponent/commit/25aad97f24d6de283ea2e3929fc9778ace8ef119

**Comment by canda** [comment]
@bcherny is there a reason why you are not using git tags to mark versions?

**Comment by bcherny** [comment]
@canda Happy to help. Not a good reason, mostly because NPM versions are sufficient for me.

**Comment by mattiascaricato** [comment]
many thanks @bcherny !

**Comment by tonyho1992** [comment]
Hey @bcherny - do you know why your links above for this fix don't seem to be working properly?

https://stackblitz.com/edit/react2angular-binding-issue-8ccxl7?file=react-component.js.
https://stackblitz.com/edit/react2angular-binding-issue-wgykee?file=react-component.js.

We're trying to add React to our Angular 1.4 library and are running into an issue where the component are not rendering (just like the two links here).
