### ISSUE TITLE
Is it not possible to pass binded functions into a React component?

### ISSUE THREAD

**Issue by pablote** [coatue-oss/react2angular#43]
I can pass a controller function just fine into react, so that it gets notified on an event:

![1](https://user-images.githubusercontent.com/2463995/31093924-ab140ea4-a789-11e7-8501-c8d72f14ad86.png)

But if I try to pass the same function binded to the controller (so I can use `this`) and to a parameter:

![2](https://user-images.githubusercontent.com/2463995/31093981-de2a4cea-a789-11e7-8ef0-19fc52a8b3bd.png)

 That doesn't seem to work, browser hangs and it keeps printing:

![screen shot 2017-10-02 at 3 47 51 pm](https://user-images.githubusercontent.com/2463995/31094004-f2f3bcec-a789-11e7-978d-cc98ae8c6b1d.png)

thanks

**Comment by bcherny** [comment]
Hi @pablote! This is an Angular issue, and is not related to React or react2angular.

I made a repro case to demonstrate: https://stackblitz.com/edit/react2angular-binding-issue-xyue5j?file=index.js.

The fix is to bind in your controller, not in your view. Otherwise every time the view is compiled you're generating a new function, so the scope gets re-digested. This is because in JavaScript:

```js
let a = function() {}
a === a.bind(a) // false
```

See the fix here: https://stackblitz.com/edit/react2angular-binding-issue-pmetca?file=index.js.

**Comment by moshfeu** [comment]
@bcherny  The fix url are not working. Can you fix it? Or supply the fix in a comment?
Thanks!

**Comment by moshfeu** [comment]
@bcherny  never mind. I figured it out. 
The answer is this stackoverflow's [question](https://stackoverflow.com/q/310870/863110)

**Comment by Oripi** [comment]
for future generations, this worked for me:
```
// angular layout
<my-comp on-close-modal-clicked="$ctrl.onCancelModalClosing"></my-comp>

// angular comp.ts
// **note the arrow function to retain context**
export class AngComp {
	onCancelModalClosing = () => {
             this.isModalDisplayed = false;
         }
}

// react component:
import * as React from 'react';

interface IProps {
	onCloseModalClicked?: () => void;
}

export default class MyComp extends React.Component<IProps> {
	closeModalClicked?: IProps['onCloseModalClicked'];
	constructor(props) {
		super(props);
	}

	closeModal = () => {
		const closeModalClicked = this.props.onCloseModalClicked;
		closeModalClicked && closeModalClicked();
	};

	render() {
		return (<Button onClick={this.props.closeModalClicked} />);
	}
}

// react2angular link
import {react2angular} from 'react2angular';
import MyComp from './my-comp';

export const myComp = react2angular(MyComp, ['onCloseModalClicked']);
```
