### ISSUE TITLE
Is it possible to have a 2-way binding with this module?

### ISSUE THREAD

**Issue by sirajulm** [coatue-oss/react2angular#47]
I've to wrap a react component inside angular, and I'm done with basic integration. But, I'd like to know if it is possible to get the data changed inside the react component back into my angular code.
While going through the `angualr2react`, this was mentioned as a caveat. 
I'd need to create a React component that will pass the data back to the parent angular code. Please let me know if that will be possible Thanks in advance.

**Comment by bcherny** [comment]
Hi @sirajulm! The most straightforward way to do it is to pass a function as a prop from your parent Angular component to your child React component. When it needs to pass data to it parent, it calls that function with the data. This is how people pass data from child -> parent in React.

Hope that helps! And if you need more help, try Googling for "react pass data from child to parent", and you'll find helpful StackOverflow posts like this one: https://stackoverflow.com/questions/38394015/how-to-pass-data-from-child-component-to-its-parent-in-reactjs.

**Comment by sirajul147** [comment]
Hi @bcherny. Thanks for the response. Yes, I'm aware of props function to pass data back to parent React component, but will that work the same from the angular wrapper component? Anyway I'll give it a try when I get time.

**Comment by bcherny** [comment]
Yup, it works the same way. See the relevant test - https://github.com/coatue-oss/react2angular/blob/ccf48bab47b4bdf030abd855f8174881c63c4bef/test.tsx#L13

**Comment by sirajul147** [comment]
Thank you. I'll go through it, and try it out soon. :)
