### ISSUE TITLE
Using angular services

### ISSUE THREAD

**Issue by shturminator** [coatue-oss/react2angular#54]
Could you please suggest an approach to use sevices/factories inside react2angular component?
Thanks.

**Comment by Sawtaytoes** [comment]
I think this is a limitation of AngularJS Components. It's similar to how Directives work, but these take a controller, and I believe the controller should give, through props, anything the component requires.

More here: https://docs.angularjs.org/guide/component

As a workaround, you should be able to pass them into the viewmodel, something like `vm.accountService = accountService` and then in the view: `<some-react-component accountService="vm.accountService" />`.

**Comment by bcherny** [comment]
Hi @shturminator! You have 2 options:

**Option 1**: Simply `import` your service/factory from your React module. For example, say your factory is (this is from https://docs.angularjs.org/guide/providers):

```js
// factory.js
myApp.factory('apiToken', ['clientId', function apiTokenFactory(clientId) {
  var encrypt = function(data1, data2) {
    return (data1 + ':' + data2).toUpperCase();
  };
  var secret = window.localStorage.getItem('myApp.secret');
  var apiToken = encrypt(clientId, secret);
  return apiToken;
}]);
```

You can update that to:

 ```js
// factory.js
var encrypt = function(data1, data2) {
  return (data1 + ':' + data2).toUpperCase();
};
var secret = window.localStorage.getItem('myApp.secret');
export var apiToken = encrypt(clientId, secret);
myApp.factory('apiToken', ['clientId', function apiTokenFactory(clientId) {
  return apiToken;
}]);
```

Then from your React component, simply import `apiToken` from factory.js. An added benefit is separating core logic from its Angular bindings.

**Option 2** is what @Sawtaytoes suggested. Just DI your service/factory, and pass it to your React component as a regular prop.

**Option 3** Once https://github.com/coatue-oss/react2angular/pull/49 is merged, DI will be supported out of the box.

**Comment by bcherny** [comment]
With v3.1.0, you can now use the extended DI syntax:

```js
react2angular(Component, props, providersToDI)
```

See example in the [docs](https://github.com/coatue-oss/react2angular#dependency-injection).

**Comment by shturminator** [comment]
Great!. Thank you for a solution. 

    On Monday, December 11, 2017, 7:23:07 PM GMT+2, Boris Cherny <notifications@github.com> wrote:  
 
 
With v3.1.0, you can now use the extended DI syntax:
react2angular(Component, props, providersToDI)
See example in the docs.

**Comment by Sawtaytoes** [comment]
What if we add `propTypes`? Do we still need to define DI in this way?

**Comment by bcherny** [comment]
@Sawtaytoes Yes, just tell react2angular to infer props from propTypes by passing `null` as the 2nd argument:

```js
class A {
}
A.propTypes = {..}

let B = react2angular(A, null, ['$http', '$log'])
```
