### ISSUE TITLE
Add Redux store to render. 

### ISSUE THREAD

**Issue by evgeny-s** [coatue-oss/react2angular#58]
Hello. 
Is it possible somehow to add Redux Store configuration, to be able to use this library with Redux?
Thank you.

**Comment by bcherny** [comment]
Hi @evgeny-s! Have you tried simply wrapping your presentational component with react2angular?

Without seeing your code, it would look something like this:

```js
let mapStateToProps = (state, ownProps) => ...
let mapDispatchToProps = (dispatch, ownProps) => ...

let FooWithRedux = connect(
  mapStateToProps,
  mapDispatchToProps
)(Foo)

let FooWithAngular = react2angular(FooWithRedux)
```

Please let me know if that works for you, or if you run into any issues.

**Comment by evgeny-s** [comment]
The problem that we havn't Redux Provider wrapper in case of using components from Angular. 
I've added store manually like this:
```Javascript
export const connectWithStore = (WrappedComponent, ...args) => {
  const ConnectedWrappedComponent = connect(...args)(WrappedComponent);
  const store = configureStore({});
  
  return (props) => (
    <ConnectedWrappedComponent {...props} store={store}/>
  );
};
```

And now I using this connect function with store connected manually, since we can't wrap everything with 
```JSX
<Provider store={store}></Provider>
```

I've found this solution here:
https://github.com/reactjs/react-redux/issues/390
