### ISSUE TITLE
How to use $scope.$on (listen for an event) 

### ISSUE THREAD

**Issue by msdark** [coatue-oss/react2angular#6]
I'm in the need to migrate a old angular 1.4 directive to a React component.
Most of the code of this directive was coded as part of the link function and are callbacks to angular events wrapped inside `$scope.$on ` 

How can I listen to that events from the react component? Is the  `$scope` "injectable" in some way ?

**Comment by bcherny** [comment]
To clarify- You are trying to rewrite an Angular component as a React component, but are not sure what to do with a listener on the component's scope? Let me know if that's right.

In either case, a code sample would be helpful, as there are a few approaches you could take depending on the situation.

**Comment by msdark** [comment]
Right. I'm trying to "translate" an angular directive to a React component. 
In this case the directive have a listener (`$scope.$on('custom:event') ` ).

code example
```javascript
var directive = function($rootScope, $window) {
return {
   template,
   restrict: 'E',
   scope: { 
      interactive: '@'
   },
  controller: function($scope){
    //do some stuff
  },
  link: function(scope, element, attrs, controller){
    scope.$on('destroy', cleanup) //clearly this can be achieved with componentWillUnMount 
    
    // This event comes from another controller that use $rootScope.$broadcast
   // Can i access to the $scope from the react component? Can $scope be passed as prop?
    scope.$on('edit-pane:toggled', function() {
       setTimeout(performTheTask, 750)
    })
  }
}```

**Comment by bcherny** [comment]
I see. I would say you have 2 good options:

1. If the event is local, pass `scope` in as a prop on your component
2. If the event is on $rootScope, use [ngimport](https://github.com/bcherny/ngimport) to import $rootScope in your React component

**Comment by bcherny** [comment]
@msdark Feel free to reopen if the above suggestions don't work for you.

**Comment by rattrayalex** [comment]
@msdark curious what you ended up going with

**Comment by bcherny** [comment]
@rattrayalex Feel free to post your code/question in this thread if I can help!

**Comment by rattrayalex** [comment]
Thanks @bcherny ! No immediate use-case, but I appreciate the offer!
