### ISSUE TITLE
Where to place react component code

### ISSUE THREAD

**Issue by skieason** [coatue-oss/react2angular#7]
Please forgive my ignorance.. I am trying to just implement the most basic sample that you have in the readme. I am unsure where to place the react component. Should it be in the same file in my angular project?

**Comment by bcherny** [comment]
You can place the React component anywhere, it doesn't matter. Take a look at the unit tests for a complete example - https://github.com/coatue-oss/react2angular/blob/master/test.tsx#L8.

Does that make sense?

**Comment by skieason** [comment]
It does! thank you so much @bcherny ! I appreciate your time in responding to my question!

**Comment by bcherny** [comment]
Happy to help!
