### ISSUE TITLE
Reorder the prop injection

### ISSUE THREAD

**Issue by ajdaniel** [coatue-oss/react2angular#72]
Hey this is a great tool and we're using this to slowly migrate from AngularJS to React.

When I use `react2angular` I love how it inspects propTypes to determine the input bindings so I don't have to repeat myself in the function call. However this breaks if I have injections, because I notice that injected props are `undefined` because I specify them in my `propTypes` because eslint fails otherwise. I think changing this line:

```js
render(<Class {...this.injectedProps} {...this.props} />, this.$element[0])
```

to this

```js
render(<Class {...this.props} {...this.injectedProps}/>, this.$element[0])
```

would fix this. it would allow me to initialize my react component with injected services without needing to specify injected props.

```js
react2angular(MyHeader, null, ['authentication', '$state', '$stateParams'])
```

**Comment by bcherny** [comment]
Hi @ajdaniel! That sound fair - PRs with tests are welcome!

**Comment by ajdaniel** [comment]
Will do!

**Comment by bcherny** [comment]
5bc181040747ab34ada436cce2ed89d9e3e257eb
