### ISSUE TITLE
Using angular expressions as value of props?

### ISSUE THREAD

**Issue by lourenci** [coatue-oss/react2angular#73]
Is there any way to using the component like this?

```javascript
<totalizer amount="{{var_of_scope}}" />
```

**Comment by wozniaklukasz** [comment]
What is the solution?

**Comment by drm-code** [comment]
I think that just passing the `var_of_scope` without curly braces takes the value from $scope of the controller, but I have an issue with that also, I'm passing a $scope value to my react component through props like this `<react-comp comments="commentList" />` but when it changes I'm not receiving the new value, gotta check deeper the code
