### ISSUE TITLE
unmet peer dependency warning

### ISSUE THREAD

**Issue by osdevisnot** [coatue-oss/react2angular#78]
It seems latest version published to NPM shows below warning:

```
warning " > react2angular@3.2.1" has unmet peer dependency "@types/prop-types@>=15".
warning " > react2angular@3.2.1" has unmet peer dependency "@types/react@>=16".
warning " > react2angular@3.2.1" has unmet peer dependency "@types/react-dom@>=16".
```
which is due to below `peerDependencies` declaration in `package.json`

```
"peerDependencies": {
    "@types/prop-types": ">=15",
    "@types/react": ">=16",
    "@types/react-dom": ">=16",
    "prop-types": ">=15",
    "react": ">=15",
    "react-dom": ">=15"
}
```

I think for **"Non Typescript Project"** it's a common practice to **NOT** install `@types/*` dependencies. Can we please remove the `@types/*` from `peerDependencies` from `package.json`?

**Comment by bcherny** [comment]
Thanks for the suggestion @osdevisnot! This is an unfortunate limitation of NPM+TS interop. If NPM had an optionalPeerDependencies (or typeDependencies) field then we could better signal that @types/... is only useful for projects that use TS.

As is, we need to have @types/... in peerDependencies so TS-based projects know to install them. For your use case, feel free to ignore the warning!
