### ISSUE TITLE
Request: Please maintain a changelog

### ISSUE THREAD

**Issue by mrobrian** [coatue-oss/react2angular#86]
I'm a big fan of this project. It is helping us convert an old Angular project into React little by little. We don't update packages very often (company policy), so when we do, we rely on change logs and release notes to know what to watch for. We had been using version 1.1.3 of react2angular, but the latest is 4.0.2. If you're following semver, I'd suspect there is the possibility of a lot of breaking changes between those two versions, but without a changelog I have no way of knowing what the changes are.

Would it be possible to have a CHANGELOG file and/or use the Releases feature of GitHub to keep track of changes?

**Comment by bcherny** [comment]
https://github.com/coatue-oss/react2angular/edit/master/CHANGELOG.md
