### ISSUE TITLE
React components in a separate npm package?

### ISSUE THREAD

**Issue by davthu** [coatue-oss/react2angular#89]
Is it possible to keep the React components in its own npm package to be included in the AngularJS project as a dependency? This way we wouldn't have to include React directly in the AngularJS project and wouldn't have to mix old code with new.

**Comment by davthu** [comment]
I figured it out, but it is not related to this project its more a npm/webpack thing.

**Comment by ma-pe** [comment]
@davthu I'd still be very interested in your solution. Do you mind adding a gist for this? Would love that!

**Comment by davthu** [comment]
@ma-pe Im just about to resumé on this work. Will post something as soon as I have something to reason about.

**Comment by manfye** [comment]
hi, how to do this? i tried import npm but it failed
