### ISSUE TITLE
NPM package dependencies

### ISSUE THREAD

**Issue by beshanoe** [coatue-oss/react2angular#9]
Hi there, I've started using react2angular and I like it :)
But package.json dependencies are quite inconsistent, first, there are @types in dependencies which are in conflict with my project's typings. I guess they're supposed to be in devDeps. Also angular version is bound strictly to 1.6.2 and higher, but I use 1.5.9 in project, maybe you could put something like `">=1.5.0"`
```
"dependencies": {
    "@types/angular": "^1.6.7",
    "@types/lodash.frompairs": "^4.0.1",
    "@types/react": "^15.0.12",
    "@types/react-dom": "^0.14.23",
    "angular": "^1.6.2",
    "lodash.frompairs": "^4.0.1",
    "ngcomponent": "^2.0.4",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
```

**Comment by bcherny** [comment]
Hi @beshanoe, thanks for the questions.

> first, there are @types in dependencies which are in conflict with my project's typings

 `@types/...`  are under `dependencies`, so that when you install react2angular, you also install the relevant typings.

 Even if you're using different versions of the typings, NPM will resolve the correct versions for you. When you say "are in conflict", what exactly do you mean? What error do you get, how are you installing react2angular, and what does your tsconfig.json look like?

> Also angular version is bound strictly to 1.6.2 and higher... maybe you could put something like ">=1.5.0"

Again, this should not cause any issues. Please see above questions.

**Comment by beshanoe** [comment]
Ok, angular's version is not a major issue for me, but regarding typings: we still yous "typings" tool for managing typings and the complete moving to @types is  planed to near future, but we want to use your tool right now and @types are causing errors about duplicated declarations.

**Comment by bcherny** [comment]
> Ok, angular's version is not a major issue for me

To be clear, it should not be an issue at all.

> @types are causing errors about duplicated declarations.

What is the exact error you are seeing? You can probably manually exclude the duplicates in your tsconfig.json. I can give a more specific suggestion with a more specific error message.

**Comment by beshanoe** [comment]
I can't be more specific right now since I'm AFK, but I got an idea, I'll just exclude this typings in tsconfig.json until we move to @types completely. Thanks!

**Comment by bcherny** [comment]
No problem - feel free to reopen if this turns out to be an issue with react2angular. Good luck!
