### ISSUE TITLE
ui-router resolve variables not injected as props

### ISSUE THREAD

**Issue by christiaanwesterbeek** [coatue-oss/react2angular#90]
Assume an AngularJS 1.7 app with components and ui-router and a state configuration like this
```javascript
.state('userlist', {
  url: '/users',
  component: 'users', // The component's name
  resolve: {
    list: function(UserService) {
      return UserService.list();
    }
  }
});
```
In AngularJS with ui-router, `list` can be bound to the component like so:
```javascript
.component('users', {
  bindings: {
    // automatically bound to `list` on the controller
    list: '<'
  },

  controller: () => { ... },
  template: `...`,
});
```

I'm attempting to migrate some AngularJS components to React components. That means, my state now looks like:

```javascript
.state('userlist', {
  url: '/users',
  component: 'reactUsers', // The react component's name
  resolve: {
    list: function(UserService) {
      return UserService.list();
    }
  }
});
```

```javascript
import { Component } from 'react'
import { react2angular } from 'react2angular'
import PropTypes from 'prop-types'

class ReactUsers extends Component {
  static propTypes = {
   list: PropTypes.array,
  };
  render() {
    console.log(this.props.list)
    return null
  }
}

angular
  .module('myModule', [])
  .component('reactUsers', react2angular(ReactUsers, ['list'], ['list']))
```

I've tried adding a propType `list` and adding `list` in the array of the 2nd parameter and 3rd parameter to react2angular. **But it isn't being injected as a prop.**

Are ui-router resolve variables not yet supported or am I missing something?

**Comment by tristanHessell** [comment]
I can't seem to reproduce this issue using AngularJS 1.7.4, ui-router 1.0.20 and react2angular 4.0.4.

Are you sure `UserService.list` returns a value?

**Comment by christiaanwesterbeek** [comment]
I was on par with those versions too. Your suggestion makes sense. I've stopped using resolves altogether for routed react components. It halts rendering the new view, so it was never a good idea to use `resolve`s. I'm now fetching data in React. I will close this issue for now since I won't put any effort into trying to reproduce the behavior. Thanks for your feedback though.
