### ISSUE TITLE
Is it possible to use material-ui components with react2angular

### ISSUE THREAD

**Issue by mberd** [coatue-oss/react2angular#94]
I am trying to replace angular material components with react material-ui and getting an error. 

index.js:
import angular from 'angular'
import Button from '@material-ui/core/Button'
import { react2angular } from 'react2angular'

angular.module('app', [])
  .component('button', react2angular(Button, ['variant', 'color']))
angular.bootstrap(document.getElementById('app'), ['app'])

index.html:
<div id="app">
	<Button variant="contained" color="primary">button text</Button>
</div>

Error:
Warning: Failed prop type: The prop `children` is marked as required in `Button`, but its value is `undefined`.
in Button (created by WithStyles(Button))
in WithStyles(Button)
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
in button (created by ButtonBase)
in ButtonBase (created by WithStyles(ButtonBase))
in WithStyles(ButtonBase) (created by Button)
in Button (created by WithStyles(Button))
in WithStyles(Button)

Demo link:

https://stackblitz.com/edit/react2angular-test?file=index.html

**Comment by lazreg87** [comment]
I'm using material-ui in my project, if you create your own component wrapping the Button it should work
