### ISSUE TITLE
Passing string angular variables as props

### ISSUE THREAD

**Issue by mgrivera** [coatue-oss/react2angular#95]
Hi all, 

I'm just trying to follow this very simple tutorial: 

[How to convert an angularJS app to React - One component at a time](https://medium.freecodecamp.org/how-to-convert-an-angular-app-to-a-react-app-one-component-at-a-time-ba985eaae66e)

In the tutorial there is an array on the angular side. Then, the image address from the array objects is passed as a prop to the react component. 

The tutorial proposes this: 

```
<div ng-repeat="item in $ctrl.bucketlist">
  <render-image image-url={{item.img}}></render-image>
</div>
```

Got this error; It seems html attribute needs quotes: 
modules.js?hash=2e5941fec7ec055edc0f054b8bc7d8b5256e45b5:16539 Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{item.img}}] starting at [{item.img}}].

If I use this: 

```
<render-image 
        image-url="{{item.img}}"
    ></render-image>
```

I think this works in plain angular, but not in react2angular. Got this: 

modules.js?hash=2e5941fec7ec055edc0f054b8bc7d8b5256e45b5:16539 Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{item.img}}] starting at [{item.img}}].

Finally, if I use this: 

```
<render-image 
        image-url="'{{item.img}}'"
    ></render-image>
```

as when using string literals: 

`<render-image baz="'baz'" foo-bar="3"></render-image>`

It just gets this in the react component:  

imageUrl: "{{item.img}}"  (this is the prop value in the react component) 

It seems it does not _resolve_ the angular expression. 

So, how can I pass an string angular variable to the html attribute, so my react component receives the value and not something like: imageUrl: "{{item.img}}??? 

Many thanks for all your help ...

**Comment by tristanHessell** [comment]
I believe that `image-url="item.img"` should work.

Can't test from where I am at the moment, can you give that a shot?

**Comment by mgrivera** [comment]
Wow Tristan, many thanks! 
I was just so confused and thought I should use interpolation here. Like in this example: 

`<a ng-href="img/{{username}}.jpg">Hello {{username}}!</a>`

Just take out the **{{** and **}}** and everything worked fine. 

Thanks again ...
