### ISSUE TITLE
Why is react listed as a peer dependency?

### ISSUE THREAD

**Issue by variousauthors** [coatue-oss/react2angular#97]
Hello! Maybe I've misunderstood what "peer dependency" means but, my understanding is that a peer dependency expresses versions of libraries which need to be installed along-side react2angular in order for it to function. But react2angular actually imports and uses React directly... shouldn't it just be a "dependency"?

Let me know if I'm crazy!

And like, the @types listed in peer dependencies... wouldn't that imply that consumers _cannot_ use react2angular outside of a typescript environment?

https://nodejs.org/en/blog/npm/peer-dependencies/
https://yarnpkg.com/en/docs/dependency-types#toc-peerdependencies

**Comment by bcherny** [comment]
https://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins

**Comment by variousauthors** [comment]
In my non-typescript app I am installing `@types/` files to support your package.
